x-backend-volumes: &backend-volumes
  - ./backend/app/:/app/

x-backend-port: &backend-port
  - "8081:8081"

x-frontend-port: &frontend-port
  - "80:80"

x-networks: &web-networks
  - web-managementnet

version: '3.8'

services:
  backend:
    image: duynguyenngoc/web-management:backend
    container_name: backend
    restart: always
    volumes: *backend-volumes
    command: sh -c "python3 main.py"
    ports: *backend-port
    networks: *web-networks

  frontend:
    image: duynguyenngoc/web-management:frontend
    environment:
      DOMAIN: localhost
      BE_HOST: backend
      BE_PORT: 8081
    container_name: frontend
    restart: always
    ports: *frontend-port
    depends_on:
      - backend
    command: sh -c "./custom_nginx.sh && nginx -g 'daemon off;'"
    networks: *web-networks
     
networks:
  web-managementnet: